name: jayajit_portfolio
description: "Official developer portfolio of Jayajit Dutta — Senior Android & Flutter Developer."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  open_file: ^3.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/resume/Jayajit_Dutta_CV.pdf
    - assets/images/picture.png
    - assets/images/crm.jpeg
    - assets/images/ghareka.jpeg
    - assets/images/pariwar.webp
    - assets/images/buildistan.jpeg
    - assets/images/massageclub.png
    - assets/images/ghareka_pmt.jpeg
